name: Release dnssw

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install UPX
      run: sudo apt-get install -y upx
        
    - name: Publish for Linux x64 (Native AOT)
      run: dotnet publish dnssw.csproj -c Release -r linux-x64 --self-contained -p:PublishAot=true -o publish/dnssw-x64

    - name: UPX Compress and Rename dnssw-x64
      run: |
        upx --best publish/dnssw-x64/dnssw 
        chmod +x publish/dnssw-x64/dnssw

    - name: Create Linux x64 Tarball
      run: |
        cd publish/dnssw-x64
        tar -czvf ../linux-x64.tar.gz dnssw
        cd ../../

    - name: Install Cross-Compilation Toolchains for ARM and ARM64 🛠️
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          llvm \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          libc6-dev-arm64-cross \
          gcc-arm-linux-gnueabihf \
          g++-arm-linux-gnueabihf \
          libc6-dev-armhf-cross \
          zlib1g-dev:arm64 \
          zlib1g-dev:armhf
          
    - name: Configure PATH for Cross-Compilation arm64
      run: |
        echo "/usr/aarch64-linux-gnu/bin" >> $GITHUB_PATH

    - name: Publish for Linux ARM64 (Native AOT)
      run: dotnet publish dnssw.csproj -c Release -r linux-arm64 --self-contained -p:PublishAot=true -o publish/dnssw-arm64

    - name: UPX Compress and Rename dnssw-arm64
      run: |
        upx --best publish/dnssw-arm64/dnssw
        chmod +x publish/dnssw-arm64/dnssw

    - name: Create Linux ARM64 Tarball
      run: |
        cd publish/dnssw-arm64
        tar -czvf ../linux-arm64.tar.gz dnssw
        cd ../../

    - name: Configure PATH for Cross-Compilation arm
      run: |
        echo "/usr/arm-linux-gnueabihf/bin" >> $GITHUB_PATH
        
    - name: Publish for Linux ARM (Native AOT)
      run: dotnet publish dnssw.csproj -c Release -r linux-arm --self-contained -p:PublishAot=true -o publish/dnssw-arm

    - name: UPX Compress and Rename dnssw-arm
      run: |
        upx --best publish/dnssw-arm/dnssw
        chmod +x publish/dnssw-arm/dnssw

    - name: Create Linux ARM Tarball
      run: |
        cd publish/dnssw-arm
        tar -czvf ../linux-arm.tar.gz dnssw
        cd ../../

    - name: Get current tag
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ steps.get_tag.outputs.TAG }}
        name: Release ${{ steps.get_tag.outputs.TAG }}
        body: |
          Compiled binaries for Linux (x64, arm64, arm).
        files: |
          publish/linux-x64.tar.gz
          publish/linux-arm64.tar.gz
          publish/linux-arm.tar.gz
